version: "3.8"

services:
  init-priv-validator-state:
    image: busybox
    restart: "no"
    command:
      [
        "sh",
        "-c",
        'mkdir -p /root/.poktroll/data/; if [ ! -f /root/.poktroll/data/priv_validator_state.json ]; then echo "{\"height\": \"0\", \"round\": 0, \"step\": 0}" > /root/.poktroll/data/priv_validator_state.json; fi; chmod -R 777 /root/.poktroll/data/',
      ]
    volumes:
      - ./poktrolld-data:/root/.poktroll/

  # Full node
  poktrolld:
    container_name: full_node
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-main}
    pull_policy: always
    # platform: "linux/amd64" # for aarch64
    command:
      - start
      - --home=/root/.poktroll/
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.laddr=0.0.0.0:26659
      - --p2p.external-address=${NODE_HOSTNAME}:26659
      - --grpc.address=0.0.0.0:26658
      - --log_level=${POKTROLLD_LOG_LEVEL}
      - --p2p.seeds=${SEEDS}
    ports:
      - "26657:26657"
      - "26658:26658"
      - "26659:26659"
    restart: unless-stopped
    depends_on:
      init-priv-validator-state:
        condition: service_completed_successfully
    volumes:
      - ./poktrolld-data:/root/.poktroll/
      - ./stake_configs/supplier_stake_config_example.yaml:/poktroll/supplier_stake_config_example.yaml
      - ./stake_configs/application_stake_config_example.yaml:/poktroll/application_stake_config_example.yaml

  # Relay Miner
  relayminer-example:
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-main}
    container_name: relay_miner
    pull_policy: always
    entrypoint: ["sh", "-c", "/root/start-relayminer.sh"]
    environment:
      - SUPPLIER_MNEMONIC=${SUPPLIER_MNEMONIC}
    ports:
      - "8545:8545" # 8545 is the port RelayMiner is configured to listen on in `relayminer_config.yaml`.
    restart: unless-stopped
    depends_on:
      - poktrolld
    volumes:
      - ./relayminer-example:/root/.poktroll/
      - ./start-relayminer.sh:/root/start-relayminer.sh

  # AppGate Server
  appgate-server-example:
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG:-main}
    container_name: appgate_server
    pull_policy: always
    entrypoint: ["sh", "-c", "/root/start-appgate-server.sh"]
    environment:
      - APPLICATION_MNEMONIC=${APPLICATION_MNEMONIC}
    ports:
      - "85:85" # 85 is the port AppGate Server is configured to listen on in `relayminer_config.yaml`.
    restart: unless-stopped
    depends_on:
      - poktrolld
    volumes:
      - ./appgate-server-example:/root/.poktroll/
      - ./start-appgate-server.sh:/root/start-appgate-server.sh
