version: '3.8'

services:
  poktrolld:
    image: ${POKTROLLD_IMAGE_REPO}:${POKTROLLD_IMAGE_TAG}
    command:
      - poktrolld
      - start
      - --home=/root/.pocket/
      - --rollkit.da_address=celestia-da:26650
      - --rollkit.da_start_height=${DA_START_HEIGHT}
      - --rollkit.da_namespace=000000000000000000000000000000000000000000${POKTROLL_NAMESPACE}
      - --rpc.laddr=tcp://0.0.0.0:36657
      - --p2p.laddr=0.0.0.0:26656
      - --p2p.external-address=${NODE_HOSTNAME}:26656
      - --grpc.address=0.0.0.0:36658
      - --log_level=${POKTROLLD_LOG_LEVEL}
      - --p2p.seeds=${SEEDS}
    ports:
      - "36657:36657"
      - "36658:36658"
      - "26656:26656"
    restart: unless-stopped
    depends_on:
      init-priv-validator-state:
        condition: service_completed_successfully
    volumes:
      - ./poktrolld-data:/root/.pocket/

  init-priv-validator-state:
    image: busybox
    restart: 'no'
    command:
      [
        'sh',
        '-c',
        'mkdir -p /root/.pocket/data/; if [ ! -f /root/.pocket/data/priv_validator_state.json ]; then echo "{\"height\": \"0\", \"round\": 0, \"step\": 0}" > /root/.pocket/data/priv_validator_state.json; fi; chmod -R 777 /root/.pocket/data/'
      ]
    volumes:
      - ./poktrolld-data:/root/.pocket/
